name: Build application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  id-token: write # Required for PyPI trusted publishing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version-file: ".python-version"

    - name: Install uv
      uses: astral-sh/setup-uv@v6.3.0
      with:
        enable-cache: true
        cache-dependency-glob: uv.lock

    - name: Sync dependencies
      run: uv sync --group dev --group test

    - uses: astral-sh/ruff-action@v3
    - run: ruff check
    - run: ruff format

    - name: Test with pytest
      run: |
        uv run pytest

    - id: version
      name: Get current version
      run: echo "initial_version=$(uv run cz version -p)" >> "$GITHUB_OUTPUT"

    - id: cz
      name: Bump version and generate changelog
      uses: commitizen-tools/commitizen-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Print new version
      run: echo "Initial ${{ steps.version.outputs.initial_version }}. Bumped to version ${{ steps.cz.outputs.version }}"

    - name: Build project
      run: uv build

    - name: Publish to PyPI
      if: ${{ ! startsWith(steps.cz.outputs.version, steps.version.outputs.initial_version) }}
      run: |
        echo "Publishing to PyPI..."
        uv publish -t ${{ secrets.PYPI_TOKEN }}
